import math

RES = WIDTH, HEIGHT = 800, 450
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = WIDTH // 2
FPS = 60

CAM_POS = 1.5, 5
CAM_ANGLE = 0

FOV = 1
HALF_FOV = FOV / 2
NUM_RAYS = WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = WIDTH // NUM_RAYS

TEXTURE_SIZE = 150
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2